export const CHANNELS = {
  TOGGLE_RECORDING: "toggle-recording",
  UI_READY: "ui-ready",
  SET_ACTIVE_VIEW: "set-active-view",
  SET_SELECTED_AUTOMATE_BOT: "set-selected-automate-bot",
  TOGGLE_SELECTED_AUTOMATE_BOT: "toggle-selected-automate-bot",
  START_AUTOMATE_BOT_FROM_STEP: "start-automate-bot-from-step",
  RUN_COORDINATE_DETECTOR: "run-coordinate-detector",
  RUN_SCREENSHOT_CAPTURE: "run-screenshot-capture",
  PICK_SCREENSHOT_SAVE_PATH: "pick-screenshot-save-path",
  GET_SCREENSHOT_SAVE_PATH: "get-screenshot-save-path",
  SET_SCREENSHOT_SAVE_PATH: "set-screenshot-save-path",
  SET_SCREENSHOT_NAME_SUFFIX: "set-screenshot-name-suffix",
  GET_DEBUG_FOLDER_FILES: "get-debug-folder-files",
  GET_ARCEUUS_BLOOD_RUNE_CONFIG: "get-arceuus-blood-rune-config",
  SET_ARCEUUS_BLOOD_RUNE_CONFIG: "set-arceuus-blood-rune-config",
  GET_GUARDIAN_OF_THE_RIFT_CONFIG: "get-guardian-of-the-rift-config",
  SET_GUARDIAN_OF_THE_RIFT_CONFIG: "set-guardian-of-the-rift-config",
  GET_GUARDIAN_OF_THE_RIFT_COLOSSAL_POUCH_FILL_COUNT:
    "get-guardian-of-the-rift-colossal-pouch-fill-count",
  SET_GUARDIAN_OF_THE_RIFT_COLOSSAL_POUCH_FILL_COUNT:
    "set-guardian-of-the-rift-colossal-pouch-fill-count",
  GET_GUARDIAN_OF_THE_RIFT_RUN_STATS: "get-guardian-of-the-rift-run-stats",
  SET_REPLAY_REPEAT: "set-replay-repeat",
  SET_REPLAY_REPEAT_COUNT: "set-replay-repeat-count",
  SET_REPLAY_CLICK_DELAY_MS: "set-replay-click-delay-ms",
  STOP_REPLAY: "stop-replay",
  TEST_COLOR_DETECTION: "test-color-detection",
  SET_ACTIVE_FILE: "set-active-file",
  CREATE_FILE: "create-file",
  RENAME_FILE: "rename-file",
  DUPLICATE_FILE: "duplicate-file",
  DELETE_FILE: "delete-file",
  UPDATE_ACTIVE_CSV_ROW: "update-active-csv-row",
  PLAY_CSV_ROW: "play-csv-row",
  MOVE_ACTIVE_CSV_ROW: "move-active-csv-row",
  MOVE_ACTIVE_CSV_ROW_TO_TOP: "move-active-csv-row-to-top",
  MOVE_ACTIVE_CSV_ROW_TO_BOTTOM: "move-active-csv-row-to-bottom",
  DELETE_ACTIVE_CSV_ROW: "delete-active-csv-row",
  INSERT_ACTIVE_CSV_ROW_ABOVE: "insert-active-csv-row-above",
  INSERT_ACTIVE_CSV_ROW_BELOW: "insert-active-csv-row-below",
  RENAME_ACTIVE_CSV_ROW_STEP: "rename-active-csv-row-step",
  REPLAY_ACTIVE_CSV: "replay-active-csv",
  REPLAY_ACTIVE_CSV_FROM_ROW: "replay-active-csv-from-row",
  RECORDING_STATE: "recording-state",
  REPLAYING_STATE: "replaying-state",
  REPLAY_REPEAT_STATE: "replay-repeat-state",
  REPLAY_REPEAT_COUNT_STATE: "replay-repeat-count-state",
  REPLAY_DELAY_STATE: "replay-delay-state",
  REPLAY_ROW_STATE: "replay-row-state",
  MARKER_COLOR_STATE: "marker-color-state",
  AUTOMATE_BOT_STATE: "automate-bot-state",
  AUTOMATE_BOT_LOG: "automate-bot-log",
  AUTOMATE_BOT_LOGS_STATE: "automate-bot-logs-state",
  OUTPUT_FOLDER_STATE: "output-folder-state",
  CURSOR_POS: "cursor-pos",
  AUTOMATE_BOT_ERROR: "automate-bot-error",
} as const;

export type Channel = (typeof CHANNELS)[keyof typeof CHANNELS];
